---
apiVersion: nais.io/v1alpha1
kind: Application
metadata:
  name: nav-dekoratoren
  namespace: personbruker
  labels:
    team: personbruker
spec:
  image: {{image}}:{{version}}
  port: 8088
  liveness:
    path: /isAlive
    initialDelay: 10
  readiness:
    path: /isReady
    initialDelay: 10
  replicas:
    min: 2
    max: 4
  ingresses:
    - https://xp.dev.nav.no
  resources:
    limits:
      cpu: '3'
      memory: 1500Mi
    requests:
      memory: 1500Mi
